### ISSUE TITLE
Location is sometimes wrongly reported

### ISSUE THREAD

**Issue by philippn** [schxslt/schxslt-redux-xslt2#1] opened 2023-06-01 11:37 UTC
Hi David,

I 've watched your presentation at MarkupUK and have quickly played around with this library. It looks very promising, thanks for your efforts.

Running it through some of our tests, it looked overall pretty good. But one weird thing is that in some cases it seemed to report the location wrong. Please find the attached testdata and inspect the output report.

If everything works as it is on my end, you will find 4 messages and each of them reports `/Q{}topic[1]/Q{}body[2]/...` as location; however, the document does not contain such a node.

Thanks for your time and kind regards,
Philipp

[schematron-and-testdata.zip](https://github.com/schxslt/schxslt-redux-xslt2/files/11624588/schematron-and-testdata.zip)

**Comment by dmj** [comment] 2023-06-02 07:46
Thanks for reporting! I can confirm that this is wrong.

**Comment by dmj** [comment] 2023-06-02 07:48
https://github.com/schxslt/schxslt-redux-xslt2/blob/7eb52c02615e6c7bcabcab720b03ea7eee3e0e60/src/main/resources/content/location.xsl#L10 -- this seems to be the culprit. I count every preceding sibling element, not just the ones of the same type.

**Comment by dmj** [comment] 2023-06-02 08:02
Hi @philippn! This issue should be fixed in version 1.0.2.

**Closed** 2023-06-02 08:02 UTC
Labels: bug
